// Created by Crowbar 0.71

// Stored modelname (without quotes): "U:\airstriptex\models\palmtree\palmtree.mdl"
$modelname "palmtree.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "palmtree_ref"
}

$flags 0

$texrendermode "palmtree.bmp" masked

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Cylinder01" -93.25 -98.900002 0 98.370003 101.650002 383.899994

$sequence "idle" {
	"palmtree_anims\idle"
	fps 15
	loop
}
