// Created by Crowbar 0.71

// Stored modelname (without quotes): "JAPANESE_FERN_01.mdl"
$modelname "pi_fern.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "FERN_reference"
}

$flags 0

$texrendermode "PLANT_FERN.BMP" masked

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Box07" -65.93 -59.27 -0.09 69.029999 71.129997 49.830002

$sequence "idle" {
	"pi_fern_anims\idle"
	fps 30
}
