// Created by Crowbar 0.71

// Stored modelname (without quotes): "U:\airstriptex\models\bush\bush.mdl"
$modelname "bush.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "bush_ref"
}

$flags 0

$texrendermode "bush.bmp" masked

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Plane03" -18.959999 -19 -29.02 15.9 16.610001 10.78

$sequence "idle" {
	"bush_anims\idle"
	fps 15
	loop
}
