// Created by Crowbar 0.71

// Stored modelname (without quotes): "U:\Counter-Strike\maps\de_quarry\models\conv\conveyor2.mdl"
$modelname "conveyor2.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "conveyor2_ref"
}

$flags 0

$texrendermode "convrail.bmp" masked

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "OBJECT07" -2.39 -76.790001 -15.19 101.599998 51.200001 28.799999

$sequence "idle" {
	"conveyor2_anims\idle"
	fps 15
	loop
}
