// Created by Crowbar 0.71

// Stored modelname (without quotes): "U:\CS\mapmodels\pallet\compile\pallet_with_bags.mdl"
$modelname "pallet_with_bags.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "pallet"
{
	studio "pallet_with_bags"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Box03" -27.26 -22.280001 -22.290001 27.34 26.629999 29.02

$sequence "idle" {
	"pallet_with_bags_anims\idle"
	fps 1
}
