// Created by Crowbar 0.71

// Stored modelname (without quotes): "U:\Counter-Strike\maps\de_piranesi\models\lamp\pi_stlamp.mdl"
$modelname "pi_stlamp.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "pi_stlamp_ref"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Cylinder01" -10 -10 -180 10 34 42

$sequence "idle" {
	"pi_stlamp_anims\idle"
	fps 15
	loop
}
