// Created by Crowbar 0.71

// Stored modelname (without quotes): "knife/w_knife.mdl"
$modelname "w_knife.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "world_knife"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bip01 Neck" -3.730872 0 -5.382515 0 1.819564 0
$hbox 0 "skin01" -0.58 -11.41 -2.32 0.57 8.86 2.12

$sequence "idle" {
	"w_knife_anims\idle"
	fps 30
}
