// Created by Crowbar 0.71

// Stored modelname (without quotes): "U:\Counter-Strike\maps\de_piranesi\models\bush\pi_shrub.mdl"
$modelname "pi_shrub.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "pi_shrub_ref"
}

$flags 0

$texrendermode "pi_bush.bmp" masked

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Plane01" -22.16 -21.690001 -23.66 21.190001 21.9 19.83

$sequence "idle" {
	"pi_shrub_anims\idle"
	fps 15
	loop
}
