// Created by Crowbar 0.71

// Stored modelname (without quotes): "valve/models/p_9mmAR.mdl"
$modelname "p_9mmar.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "reference_mp5"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bip01 Neck" -2.869898 0 -4.140396 0 1.399663 0
$hbox 0 "Line02" -7.61 -6.11 -0.53 12.38 5.2 1.6

$sequence "idle" {
	"p_9mmar_anims\idle"
	fps 30
}
