// Created by Crowbar 0.71

// Stored modelname (without quotes): "models/Cstrike/dummyguerilla.mdl"
$modelname "dummyguerilla.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "guerillabody"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "BODY01" -36.59 -6.14 -44.970001 36.610001 7.51 23.76

$sequence "idle" {
	"dummyguerilla_anims\idle"
	fps 30
}
