// Created by Crowbar 0.71

// Stored modelname (without quotes): "U:\Counter-Strike\maps\de_quarry\models\loader\qloader.mdl"
$modelname "qloader.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "qloader_ref"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "a01" -130.380005 -55.48 -62.09 97.550003 49.98 20.639999

$sequence "idle" {
	"qloader_anims\idle"
	fps 15
	loop
}
