// Created by Crowbar 0.71

// Stored modelname (without quotes): "U:\Counter-Strike\maps\de_piranesi\models\lamp\pi_outlamp1.mdl"
$modelname "pi_outlamp1.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "pi_outlamp1_ref"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Cylinder01" -10 -10 0 10 23.99 40

$sequence "idle" {
	"pi_outlamp1_anims\idle"
	fps 15
	loop
}
