// Created by Crowbar 0.71

// Stored modelname (without quotes): "U:\Counter-Strike\maps\de_airstrip\models\fern\fern.mdl"
$modelname "fern.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "fern_ref"
}

$flags 0

$texrendermode "fern.bmp" masked

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Plane02" -42.57 -9.11 -38.169998 40.450001 14.63 41

$sequence "fern_idle" {
	"fern_anims\fern_idle"
	fps 15
	loop
}
