// Created by Crowbar 0.71

// Stored modelname (without quotes): "u:\dod\models\mapmodels\iikka\bigtree.mdl"
$modelname "bigtree.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "bigtree_ref"
}

$flags 0

$texrendermode "bigtree.bmp" masked

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Object01" -146.350006 -135.289993 -141.899994 153.869995 144.550003 271.320007

$sequence "bigtree_idle" {
	"bigtree_anims\bigtree_idle"
	fps 15
	loop
}
