// Created by Crowbar 0.71

// Stored modelname (without quotes): "m3super90/p_m3super90.mdl"
$modelname "p_m3super90.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "reference_m3super90"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bip01 Neck" -2.869902 0 -4.140396 0 1.399665 0
$hbox 0 "skin01" -0.72 -12.49 -5.43 0.67 21.719999 2.84

$sequence "idle" {
	"p_m3super90_anims\idle"
	fps 30
}
