// Created by Crowbar 0.71

// Stored modelname (without quotes): "lshrub.mdl"
$modelname "pi_bush.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "lshrub_ref"
}

$flags 0

$texrendermode "leaves9.bmp" masked

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "default" -24.780001 -24.16 -0.11 24.65 23.549999 42.869999

$sequence "idle" {
	"pi_bush_anims\idle"
	fps 20
}
