// Created by Crowbar 0.71

// Stored modelname (without quotes): "U:\Counter-Strike\maps\de_quarry\models\conv\support3.mdl"
$modelname "support3.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "support3_ref"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "OBJECT104" -46 -2 -70 46 1.99 182

$sequence "idle" {
	"support3_anims\idle"
	fps 15
	loop
}
