// Created by Crowbar 0.71

// Stored modelname (without quotes): "u:\dod\models\mapmodels\narby\PG-150.mdl"
$modelname "PG-150.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "PG-150_ref"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Cessna" -201.75 -155.190002 -32.91 201.470001 147.419998 71.790001

$sequence "PG-150_idle" {
	"PG-150_anims\PG-150_idle"
	fps 1
}
