// Created by Crowbar 0.71

// Stored modelname (without quotes): "U:\Counter-Strike\maps\de_airstrip\models\grass\grass.mdl"
$modelname "grass.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "grass_ref"
}

$flags 0

$texrendermode "grassblades.bmp" masked

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "grassblades" -21.02 -17.809999 -19.75 18.709999 21.4 27.6

$sequence "grass_idle" {
	"grass_anims\grass_idle"
	fps 15
	loop
}
