// Created by Crowbar 0.71

$modelname "p_m3.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "reference_m3super90"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bip01 R Hand" 0 -2.192649 -2.03543 28.365305 0 0
$hbox 0 "flash" -12.540333 -4.91095 0 0 0 3.640697
$hbox 0 "skin01" -0.61 -12.98 -5.22 0.6 22.620001 3.05

$sequence "idle" {
	"p_m3_anims\idle"
	fps 30
}
