// Created by Crowbar 0.71

// Stored modelname (without quotes): "U:\Counter-Strike\maps\de_piranesi\models\treeb\pi_treeb.mdl"
$modelname "pi_treeb.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "pi_treeb_ref"
}

$flags 0

$texrendermode "{pi_treeb.bmp" masked

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Cylinder01" -184.610001 -160.389999 0 158.889999 169.369995 493.700012

$sequence "idle" {
	"pi_treeb_anims\idle"
	fps 15
	loop
}
