// Created by Crowbar 0.71

// Stored modelname (without quotes): "U:\CS\mapmodels\truck\compile\truck.mdl"
$modelname "qtruck.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "truck"
{
	studio "reference"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "skin2" -56.650002 -162.369995 -63.459999 56.32 177.050003 46.720001

$sequence "idle" {
	"qtruck_anims\idle"
	fps 1
}
