// Created by Crowbar 0.71

// Stored modelname (without quotes): "U:\Counter-Strike\maps\de_quarry\models\conv\conveyor_turn.mdl"
$modelname "conveyor_turn.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "conveyor_turn_ref"
}

$flags 0

$texrendermode "convrail.bmp" masked

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "OBJECT07" -258.390015 -76.800003 -15.19 101.589996 283.200012 28.799999

$sequence "idle" {
	"conveyor_turn_anims\idle"
	fps 15
	loop
}
