// Created by Crowbar 0.71

// Stored modelname (without quotes): "U:\Counter-Strike\maps\de_piranesi\models\tree\pi_tree.mdl"
$modelname "pi_tree.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "pi_tree_ref"
}

$flags 0

$texrendermode "pi_tree.bmp" masked

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Cylinder01" -226.149994 -254.039993 -0.82 219.190002 220.25 616.809998

$sequence "idle" {
	"pi_tree_anims\idle"
	fps 15
	loop
}
