// Created by Crowbar 0.71

// Stored modelname (without quotes): "U:\Counter-Strike\maps\de_piranesi\models\twig\twig.mdl"
$modelname "pi_twig.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "twig_ref"
}

$flags 0

$texrendermode "twig.bmp" masked

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Cylinder01" -17.129999 -15.86 0 19.18 18.389999 45.16

$sequence "idle" {
	"pi_twig_anims\idle"
	fps 15
	loop
}
