// Created by Crowbar 0.71

// Stored modelname (without quotes): "U:\Counter-Strike\maps\de_quarry\models\conv\conveyor3.mdl"
$modelname "conveyor3.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "conveyor3_ref"
}

$flags 0

$texrendermode "convrail.bmp" masked

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "OBJECT07" -2.39 -588.789978 -246.720001 101.599998 51.200001 49.27

$sequence "idle" {
	"conveyor3_anims\idle"
	fps 15
	loop
}
